title: FlareonzVerse
author: Flareonz44
url: https://flareonz44.github.io
permalink: /:slug

favicon: "./logo.png"

theme_config:
  back_home_text: "↩ back"
  date_format: "%Y-%m-%d"

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed